version: "3.9"
services:
  evolution:
    image: atendai/evolution-api:latest
    container_name: evolution
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      SERVER_PORT: "8080"
      AUTHENTICATION_API_KEY: "${AUTHENTICATION_API_KEY}"
      SWAGGER_ENABLED: "true"
    volumes:
      - evolution-data:/evolution/storage
volumes:
  evolution-data:
